### ISSUE TITLE
When will the evaluation code and baseline be released?

### ISSUE THREAD

**Issue by Shallow2000** [Ali2500/BURST-benchmark#1]

**Comment by Ali2500** [comment]
Hi, the eval code is not really in a presentable state right now mainly because most of us are busy with CVPR submissions (deadline 11 Nov). After that we will push the eval code for BURST to TrackEval.

Sorry for the inconvenience.

**Comment by Shallow2000** [comment]
Ok. Thank you!

**Comment by Ali2500** [comment]
UPDATE: The evaluation code is now available.
