### ISSUE TITLE
Datasets for semi-supervised video object segmentation

### ISSUE THREAD

**Issue by z-jiaming** [Ali2500/BURST-benchmark#10]
Could you please tell me how to convert json to mask in DAVIS-format, like first_frame_annotations.json?
And how to convert the mask prediction to json for evaluating?

If possible, it would greatly facilitate BURST's research in VOS.

Thanks a lot!!!

**Comment by Ali2500** [comment]
Hi, you can inspect the format by opening up the JSON file in Firefox. It will show you how the lists and dictionaries are organized. The format is also documented in ANNOTATION_FORMAT.md. To see how you can parse the RLE-encoded mask into an image see this method: https://github.com/Ali2500/BURST-benchmark/blob/main/burstapi/utils.py#L21

**Comment by z-jiaming** [comment]
I found that the video numbers in first_frame_annotations.json and all_classes.json of test are different in ArgoVerse.
What's the reason for this?

Thanks!

<img width="1727" alt="image" src="https://github.com/Ali2500/BURST-benchmark/assets/42411674/7841f6a2-af11-4575-ad27-53fb6b44e90d">


<img width="1773" alt="image" src="https://github.com/Ali2500/BURST-benchmark/assets/42411674/1bec321f-d91c-4862-a293-42413db3636e">

**Comment by Ali2500** [comment]
The test set contains some videos which do not have any ground-truth annotations. Consequently, these videos are not present in the `first_frame_annotations.json` file.

**Comment by z-jiaming** [comment]
So, if my predictions.json dosen't contain these removed video, the eval result is also correct?

**Comment by Ali2500** [comment]
Yes it should be.

**Comment by z-jiaming** [comment]
Got it. Thanks!
