### ISSUE TITLE
Training setting

### ISSUE THREAD

**Issue by z-jiaming** [Ali2500/BURST-benchmark#11]
Hi, thanks for your work.
I want to know the training setting of your STCN baseline in mask-based Exemplar Guided, i.e., 49.8 HOTA_all?
Is it just trained on BURST training set, or just using off-the-shelf STCN model trained on DAVIS&YouTube-VOS?

Thanks!!

**Comment by Ali2500** [comment]
The STCN baseline was generated using off-the-shelf weights trained by the authors on DAVIS+YouTubeVOS
