### ISSUE TITLE
Extension of Video Panoptic Segmentation

### ISSUE THREAD

**Issue by HYUNJS** [Ali2500/BURST-benchmark#2]
Hi, thank you for your great effort in unifying the tracking & segmentation communities. I would like to ask that do you have any plan to extend the BURST dataset, for example, including more annotations to unify the video panoptic segmentation task into the benchmark?

**Comment by Ali2500** [comment]
Hi, 
So far we do not have any plans of extending the dataset for panoptic segmentation. I imagine that doing so would be extremely laborious given the number and length of videos in the dataset.

**Comment by HYUNJS** [comment]
Thank you for your answer :)
