### ISSUE TITLE
Question about number of classes in open-world settings

### ISSUE THREAD

**Issue by sumcher-ng** [Ali2500/BURST-benchmark#7]
Thank you for your great work! 
I have a question about the numbers of common and uncommon classes. There are 78 common classes, but there are only 64 common and 418 uncommon classes in _info/class_split.json_. I tried to load _test/common_classes.json_ and _val/common_classes.json_ too, but the numbers are not 78 as reported in the paper.

**Comment by Ali2500** [comment]
TAO/BURST are mainly intended for evaluation, so there are several classes which are present in val/test, but not in train. For training purposes, it'd be better to utilize the LVIS image dataset for pre-training, in addition to the BURST training set.

**Comment by sumcher-ng** [comment]
I got it. Thank you!
