### ISSUE TITLE
[Question] The sequence number of annotations is inconsistent with describtion in paper.

### ISSUE THREAD

**Issue by clownrat6** [Ali2500/BURST-benchmark#8]
As mentioned in paper, the validation set of BURST dataset contains 993 videos. But the validation annotations ("all_classes.json") only contains 988 videos. I hope that author can explain my doubts. Thanks!

**Comment by Ali2500** [comment]
Hi, yes this inconsistency is unfortunately there, but the annotations file is correct and there are 988 videos in val.

**Comment by clownrat6** [comment]
Thanks for your reply!
